site_name: llamafile

repo_url: https://github.com/mozilla-ai/llamafile
repo_name: llamafile

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Example llamafiles: example_llamafiles.md
  - Running a llamafile: running_llamafile.md
  - Creating llamafiles: creating_llamafiles.md
  - Source installation: source_installation.md
  - Technical details: technical_details.md
  - Supported Systems: support.md
  - Troubleshooting: troubleshooting.md
  - Whisperfile:
    - Overview: whisperfile/index.md
    - Getting Started: whisperfile/getting-started.md
    - Packaging: whisperfile/packaging.md
    - Using GPUs: whisperfile/gpu.md
    - Translation: whisperfile/translate.md
    - Server: whisperfile/server.md

theme:
  name: material
  font:
    text: Noto Sans
    code: Noto Sans Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - accent: blue
  logo: images/llamafile-640x640.png
  favicon: images/llamafile-640x640.png
  features:
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - navigation.expand
    - navigation.footer
    - navigation.sections

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

plugins:
  - search

edit_uri: edit/main/docs/
